name: 'SBOM Action'
description: 'Diff SBOMs'
author: 'Peter Wagner'
inputs:
  sbom:
    description: 'local path to sbom for comparison'
    default: 'cyclonedx.json'
  base-image:
    description: 'remote image for sbom for comparison'
    default: ghcr.io/${{github.repository}}:latest
  token:
    description: GitHub token
    default: ${{ github.token }}
  certificate-identity-regexp:
    description: 'regexp to match certificate identity'
    default: '.*'
  certificate-oidc-issuer-regexp:
    description: 'regexp to match certificate identity'
    default: '.*'

runs:
  using: 'node20'
  main: 'dist/index.js'
