name: 'SBOM Action'
description: 'Diff SBOMs'
author: 'Peter Wagner'
inputs:
  milliseconds: # FIXME: finish this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
