name: 'SBOM Action'
description: 'Diff SBOMs'
author: 'Peter Wagner'
inputs:
  sbom:
    description: 'local path to sbom for comparison'
    default: 'cyclonedx.json'
  base-image:
    description: 'remote image for sbom for comparison'
    default: ghcr.io/${{github.repository}}:latest
  token:
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
